### ISSUE TITLE
[Feature]: Create Separate folder for controllers

### ISSUE THREAD

**Issue by devraushan** [OPCODE-Open-Spring-Fest/InsecureNet#4]
### So, what is it about?

Currently all the controllers are present in the single file named routes which makes our codebase look messy
Need a separate folder for different controllers which will make our codebase more organised.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdityaKumar5155** [comment]
You have 8 working hours to complete this issue otherwise it will be forwarded to other contributor.

**Comment by devraushan** [comment]
okk thank you sir
I'm working out on it
